// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetAtAccuracyEnum } from "./MetAtAccuracyEnum";

export interface Friend { id: string, first_name: string, last_name: string, date_of_birth: string, created_at: string, updated_at: string, met_at: string, met_at_accuracy: MetAtAccuracyEnum | null, }