// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FriendIdeaTypeEnum } from "./FriendIdeaTypeEnum";

export interface NewFriendsIdea { friend_id: string, content: string, idea_type: FriendIdeaTypeEnum, }