// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface NewUser { first_name: string, last_name: string, date_of_birth: string, }