// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Paginated<T> { items: T, current_page: number, per_page: number, total_items: number, total_pages: number, offset: number, has_next_page: boolean, has_prev_page: boolean, }