// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FriendIdeaTypeEnum } from "./FriendIdeaTypeEnum";

export interface FriendsIdea { id: string, content: string, created_at: string, updated_at: string, friend_id: string, idea_type: FriendIdeaTypeEnum, }